/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE customersBaseService PLEASE EDIT ../customers.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Customers } from '../../domain/dr-app_db/customers';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Customers.service.ts
 */

/*
 * SCHEMA DB Customers
 *
	{
		Email: {
			type: 'String',
			required : true
		},
		Name: {
			type: 'String',
			required : true
		},
		NationalID: {
			type: 'String'
		},
		Passport: {
			type: 'String'
		},
		Phone: {
			type: 'Number',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class CustomersBaseService {

    private customersCollection: AngularFirestoreCollection<Customers>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.customersCollection = afs.collection<Customers>('customers');
    }


    // CRUD METHODS

    /**
    * CustomersService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Customers): Promise<DocumentReference> {
        return this.customersCollection.add(item);
    }

    /**
    * CustomersService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.customersCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * CustomersService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Customers> {
        return this.afs.doc<Customers>('customers/' + id);
    }

    /**
    * CustomersService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Customers[]> {
        return this.afs.collection('customers').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Customers;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * CustomersService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Customers>, item: Customers): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
