/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE staffBaseService PLEASE EDIT ../staff.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Staff } from '../../domain/dr-app_db/staff';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Staff.service.ts
 */

/*
 * SCHEMA DB Staff
 *
	{
		ActivityLog: {
			type: 'String'
		},
		Name: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class StaffBaseService {

    private staffCollection: AngularFirestoreCollection<Staff>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.staffCollection = afs.collection<Staff>('staff');
    }


    // CRUD METHODS

    /**
    * StaffService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Staff): Promise<DocumentReference> {
        return this.staffCollection.add(item);
    }

    /**
    * StaffService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.staffCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * StaffService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Staff> {
        return this.afs.doc<Staff>('staff/' + id);
    }

    /**
    * StaffService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Staff[]> {
        return this.afs.collection('staff').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Staff;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * StaffService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Staff>, item: Staff): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
