/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE vehiclesBaseService PLEASE EDIT ../vehicles.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Vehicles } from '../../domain/dr-app_db/vehicles';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Vehicles.service.ts
 */

/*
 * SCHEMA DB Vehicles
 *
	{
		DateJoined: {
			type: 'Date'
		},
		Manufacturer: {
			type: 'String',
			required : true
		},
		Model: {
			type: 'String'
		},
		Registration: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class VehiclesBaseService {

    private vehiclesCollection: AngularFirestoreCollection<Vehicles>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.vehiclesCollection = afs.collection<Vehicles>('vehicles');
    }


    // CRUD METHODS

    /**
    * VehiclesService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Vehicles): Promise<DocumentReference> {
        return this.vehiclesCollection.add(item);
    }

    /**
    * VehiclesService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.vehiclesCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * VehiclesService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Vehicles> {
        return this.afs.doc<Vehicles>('vehicles/' + id);
    }

    /**
    * VehiclesService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Vehicles[]> {
        return this.afs.collection('vehicles').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Vehicles;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * VehiclesService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Vehicles>, item: Vehicles): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
